### ISSUE TITLE
useFormSetter for Dynamic Form Value Handling

### ISSUE THREAD

**Issue by Villarley** [StarShopCr/StarShop-Frontend#2]
Implement a custom hook called useFormSetter to dynamically set form field values. The hook should accept a field identifier (name or key) and allow updating the form state easily.

**Comment by KevinLatino** [comment]
Can i help?

**Comment by Villarley** [comment]
@KevinLatino assigned to you. You have 24 hours to make it

**Comment by drakkomaximo** [comment]
Why invest in a custom hook for form handling when there are already optimized libraries like Formik or React Hook Form that fulfill this purpose and offer more intuitive functionality?
