### ISSUE TITLE
[FE]: Implement Landing Page Screen 

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#24]
> [!IMPORTANT]
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Implement Landing Page Screen

## Description  
Implement the landing page design that showcases the key features of our application while maintaining a modern, user-friendly, and professional look.

## Requirements  
You have to:  
- Please use the route and component that are already created (route `"/"`, and component: `src/components/landing-page/LandingComponent.tsx`).
- Follow the provided [Figma design](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=3ezkHD2wXRwtQ15L-0), you have to use the `Landing Page` Frame.  

## Deliverables  
- Finalized implementation based on the Figma design.  
- Responsive and functional layout ready for testing.  

## Additional Notes  
Stick to the design provided in Figma and maintain consistency with the brand's visual identity. Suggestions for improvement are welcome if they align with the project's goals.  

## Image: 
<img width="893" alt="Captura de pantalla 2024-12-08 a las 7 37 30 p  m" src="https://github.com/user-attachments/assets/d069898d-5d78-4642-80b8-a26e570f1619" />

**Comment by sonkeydotcom** [comment]
Happy to take this

**Comment by sonkeydotcom** [comment]
ETA: 2-3 days. I will implement a responsive landing page based on the Figma design, including a navigation bar, hero section with CTA, and a features section showcasing key app benefits. The footer will feature contact details and social links, and I’ll ensure the page is fully responsive and tested across devices.

**Comment by hoangkianh** [comment]
Can I start working on this?

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by robertram** [comment]
Hi, I am from de Dojo Coding community and a new contributor to Only Dust. Im a web3 frontend developer and founder of a NFT ticketing platform. 
ETA: 2-3 days.
The way I would approach this is follow the design guidelines from the Figma file, download the required assets, and implement the mobile, tablet and desktop design. I will test on different devices.

**Comment by mymiracle0118** [comment]
Let me try this one!

**Comment by ozo-vehe** [comment]
Can I contribute to this one? I am a front-end developer with a proven track record of building highly responsive, mobile-first, user-friendly landing pages.

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 2-3 days.
Plan:
Analyze Design: Carefully review the Figma design and understand its structure, ensuring alignment with the brand’s visual identity.

Develop Structure: Use the LandingComponent.tsx file and build the page layout as per the design, focusing on user-friendly navigation and a professional look.

Implement Key Features: Highlight the application's features prominently while ensuring a responsive layout for various devices.

Styling and Consistency: Apply consistent styles using CSS/Tailwind, adhering strictly to the branding guidelines and maintaining design fidelity.

Testing and Review: Validate the page’s responsiveness, accessibility, and functionality across devices and browsers. Provide suggestions for improvement if relevant.

Submit Deliverables: Deliver a finalized implementation ready for testing and review

**Comment by drakkomaximo** [comment]
Hi everyone!

I’d love to work on implementing the landing page. With over 5 years of frontend experience, I’ve created modern, responsive designs that are user-friendly and align with branding guidelines.

Estimated time: 1-2 days

How I’ll approach it:

1. Use the existing route ("/") and LandingComponent.tsx file.
2. Follow the Figma design closely, ensuring it’s responsive and matches the brand’s style.
3. Deliver a polished layout, ready for testing, while suggesting any improvements that align with the project goals.

Let me know if I can get started!

**Comment by Holamite** [comment]
I’m passionate about making Web3 technology more accessible because I believe user experience is one of the biggest barriers to bringing new users into the decentralized world. That’s why I focus on creating user-friendly applications.

## Solution plan
I’ll start by carefully reviewing the Figma design to fully understand the flow and design details. I’ll use the existing route ("/") and LandingComponent.tsx to keep the implementation clean. My goal will be to create a responsive layout that looks great and works smoothly on any device. Once the design is implemented, I’ll test it thoroughly to make sure it’s functional, polished, and ready to go.

5-6 hours to complete

**Comment by josephchimebuka** [comment]
I'd love to work on this!

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub and the Figma design, 
- I will write the code to create the LandingPage UI in the `LandingComponent.tsx` file.
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices

## ETA
3-4 Hours

**Comment by robertram** [comment]
Hi, I am from de Dojo Coding community and a new contributor to Only Dust. Im a web3 frontend developer and founder of a NFT ticketing platform. 
ETA: 1-2 days.
The way I would approach this is follow the design guidelines from the Figma file, download the required assets, and implement the mobile, tablet and desktop design. I will test on different devices.

**Comment by Ayoazeez26** [comment]
I am a software developer with over 5 years experience building applications. I intend on tackling this issue by modifying the LandingComponent.tsx file to implement the landing page design following the figma file to pixel perfect implementation. I will also make sure the page is fully responsive before making a PR
ETA - 2 days.

**Comment by ozo-vehe** [comment]
Estimated completion time: 1-3 days

To implement the Landing Page Screen, I will:

1. Review the Figma design for the Landing Page.
2. Edit the existing LandingComponent.tsx file to match the design.
3. Implement the key features and sections as outlined in the design.
4. Ensure a responsive and functional layout.
5. Maintain consistency with the brand's visual identity.
6. Test the page for layout and visual consistency with the Figma design.

**Comment by SYLVIANNORUKA** [comment]
Is it okay if I tackle this?
I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by kcmikee** [comment]
Would love to tackle this!

**Comment by armandocodecr** [comment]
### **📬 Issue Submission: Implement Landing Page Screen**

I propose implementing the landing page in src/components/landing-page/LandingComponent.tsx, following the Figma design and brand guidelines. The layout will be responsive, modern, and highlight key features effectively. Having experience with similar implementations, I estimate completing this task in **4 days**. The final result will be ready for testing and suggestions for improvement are welcome if aligned with project goals.

**Comment by Emmykeyz101** [comment]
I’d like to help with this.

**Comment by SudiptaPaul-31** [comment]
I think I can work on this issue

My approach:

Will first start by looking the figma file and try to replicate it and add all the css properties and making it responsive throughout all device and finally end up by making a pr

ETA: 2days

**Comment by caxtonacollins** [comment]
Is it okay if I tackle this? this will be my first time contributing.

**Comment by abdegenius** [comment]
Can I handle this task?

**Comment by vestor-dev** [comment]
Can I tackle this one?
would love to work on this

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 2-3 days.
Plan:
Analyze Design: Carefully review the Figma design and understand its structure, ensuring alignment with the brand’s visual identity.

Develop Structure: Use the LandingComponent.tsx file and build the page layout as per the design, focusing on user-friendly navigation and a professional look.

Implement Key Features: Highlight the application's features prominently while ensuring a responsive layout for various devices.

Styling and Consistency: Apply consistent styles using CSS/Tailwind, adhering strictly to the branding guidelines and maintaining design fidelity.

Testing and Review: Validate the page’s responsiveness, accessibility, and functionality across devices and browsers. Provide suggestions for improvement if relevant.

Submit Deliverables: Deliver a finalized implementation ready for testing and review

**Comment by starknetbrother** [comment]
Can I take this from here?

**Comment by chigozzdevv** [comment]
Can I take care of this issue?

**Comment by Michaelkingsdev** [comment]
I’m interested in this one.

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, Typescript, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.

I have worked with many pages similar to this one so I am familiar with the topic. My approach is the following, first I will go to the specified path, where I will implement the layout that the maintainer defined in figma for the theme and I will create the page according to the style and design according to the other elements of the project, I will make sure that it is consistent and faithful to the design.

**Comment by 3th-Enjay** [comment]
May I handle this issue?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a front-end developer with experience in building responsive and user-friendly landing pages. I am confident that I can implement the landing page for this project, adhering to the provided Figma design and ensuring that the page is modern, professional, and functional.

I will follow the given design and ensure the layout is responsive and user-friendly. The final implementation will be fully functional and ready for testing ETA 1 DAY
Please assign me this task, and I look forward to contributing to the project!

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe I can take on this task

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies. My expertise includes: Nuxt.js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. I would love to contribute to this project.

How I plan on tackling this issue
My approach towards this issue after forking the repo and creating the branch I would work on, would be to first export the background image and other assets (like the image on the right, and the colours). I would then set the image as the background. I would import the navbar component from the src/components/ui before I would now create a div for the body which would be on flex so that I can have my text and button on the left and the image on the right.  ETA is 24hrs

**Comment by kayceeDev** [comment]
I’m interested in this one.

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by building the "Landing page" to be according to the figma design and to be mobile responsive. ETA 2 days

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer with expertise in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I will implement the landing page screen as per the Figma design, ensuring responsiveness and functionality. I'll use the existing route and component (/ and src/components/landing-page/LandingComponent.tsx) to maintain consistency.

Please assign this issue to me.

Thank you!

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by sonkeydotcom** [comment]
ETA: 2-3 days. I will implement a responsive landing page based on the Figma design, including a navigation bar, hero section with CTA, and a features section showcasing key app benefits. The footer will feature contact details and social links, and I’ll ensure the page is fully responsive and tested across devices.

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.
I will first understand the design and use my front-end skills to interpret it by using the image and the font used in the design and make sure I route it using my routing skill.
Ask question from maintainer if I don't understand anything.

**Comment by Gladchux14** [comment]
hello! my name is Gladchux.
I have extensively used JavaScript and typescript to deliver quality and responsive interactive projects.

 I have worked and delivered amazing landing pages for my team during projects , check my GitHub: https://github.com/Gladchux14.

My plan to resolve this issue:
create a branch after cloning the repository.
Study the codebase to understand it.
locate already created components for  the landing page.
build/design the landing page ensuring consistency with figma design.
implement styling from the design.
ensure responsiveness for all screen sizes.
raise an explicit PR and notify maintainers.

my ETA for this would be 2 days.
i really look forward to working and  delivering this!

**Comment by KevinLatino** [comment]
@robertram task assigned to you. Let me know if you need further clarification or additional support!😊
Here is our telegram group, please join https://t.me/starshopcr
