### ISSUE TITLE
[FE]: Create Connect Wallet Button logic

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#25]
> [!IMPORTANT]
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Create Connect Wallet Button Logic  

## Description  
Implement the logic for a "Connect Wallet" button to enable users to connect to Stellar wallets. The button should support wallets such as **Albedo**, **Rabet**, **Freighter**, and other Stellar-compatible wallets.  

## Requirements  
1. **Component Location**:  
   - The Component is located in `components/ui/ConnectWalletButton.tsx` (you have to edit the .tsx file).  

2. **Functionality**:  
   - Allow users to select and connect to their preferred Stellar wallet.  
   - Detect and handle cases where a wallet is not installed.  
   - Use best practices for Stellar wallet integrations.  

3. **UI Design**:  
   - Ensure the button is styled consistently with the application's theme, Follow the provided [Figma design](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=pVTHQecm3MDfgGXN-0).  
   - Use clear and concise text like “Connect Wallet” or similar.  

4. **Wallet Support**:  
   - Integrate with popular Stellar wallets, including but not limited to:  
     - **Albedo**  
     - **Rabet**  
     - **Freighter**  
     - **Xbull**  

### Image:
<img width="598" alt="Captura de pantalla 2024-12-08 a las 7 39 47 p  m" src="https://github.com/user-attachments/assets/067a5136-eee6-4a78-a9f3-80a717b5bfb8" />

**Comment by hoangkianh** [comment]
Could I take a shot at this?

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by mymiracle0118** [comment]
Can I take care of this issue?

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 2-3 days.
Plan:
Analyze Wallet APIs: Research and integrate the APIs or SDKs for Stellar-compatible wallets (Albedo, Rabet, Freighter, and Xbull).

Implement Wallet Selection: Enhance ConnectWalletButton.tsx to allow users to select their preferred wallet using a dropdown or modal.

Detect Wallet Availability: Add logic to detect if the selected wallet is installed, and show clear error messages if not.

Handle Connections: Establish secure wallet connections using best practices for Stellar wallet integration, including handling authentication and account retrieval.

UI Design: Style the button and any additional UI elements (e.g., modals) to align with the Figma design and the application's theme. Use clear text such as “Connect Wallet.”

Testing: Test the integration thoroughly across all supported wallets to ensure seamless functionality and user experience.

Submit Deliverables: Ensure all code is clean, well-documented, and ready for review.

**Comment by josephchimebuka** [comment]
Could I take on this issue?

**Comment by ryzen-xp** [comment]
Hi, 
I’m a blockchain developer skilled in Cairo, Rust, Solidity, and web development, with contributions to projects like Chainevents and Arkprojects etc.
I can implement the "Connect Wallet" button logic, integrating Stellar wallets and following the app’s design. Please assign this issue to me.
Thank you!

**Comment by JosueBrenes** [comment]
## [FE]: Modify Metadata

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take less than 1 day to complete.

---

### Steps to Resolve

1. **Locate the RootLayout File**  
   - Open the file `src/app/layout.tsx` where the metadata for the application is currently defined.

2. **Update Metadata**  
   - Replace the existing metadata with the following values:
     - **Title:** `"StarShop"`  
     - **Description:** `"Empowering users to buy and sell unique digital assets on a blockchain-based marketplace, fostering transparency and trust through NFTs."`

3. **Validate the Changes**  
   - Run the application locally to ensure that:
     - The title appears correctly in the browser tab.
     - The description is updated in the page source under the `<meta>` tag.

4. **Commit and Submit**  
   - Create a new branch named `feature/metadata-update`.  
   - Commit the changes with an appropriate commit message.  
   - Open a pull request and describe the update made to the metadata.

---

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by kcmikee** [comment]
Can I take this from here?

**Comment by kimcascante** [comment]
Hi @KevinLatino I'm Kimberly Cascante, a proud member of Dojo Coding! ⛩️
I have previously worked with TypeScript, including implementing conditional logic to disable buttons based on specific criteria. I'm passionate about design and frontend development and excited to contribute to this project.
My plan is to start by reviewing the Component, then proceed to edit it, following the project's structure and figma design. I'll ensure proper validations, test the solution, and prepare a PR for review.
I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by armandocodecr** [comment]
### **📬 Issue Submission: Connect Wallet Button Logic**

I propose implementing the **Connect Wallet** button in components/ui/ConnectWalletButton.tsx to support **Albedo**, **Rabet**, **Freighter**, and **Xbull** wallets. The solution will handle wallet selection, connection, and error scenarios while following best practices and the Figma design. Having experience with similar wallet integrations, I estimate completing this task in **4 days**. The button will provide clear feedback, handle missing wallets gracefully, and maintain a seamless user experience.

**Comment by Emmykeyz101** [comment]
I can do this

**Comment by zintarh** [comment]
Can I jump on this task?

**Comment by emarc99** [comment]
I'd be happy to do this. Let me do this. Eta - 2 days. Have experience doing wallet connect with reown, wagmi, 3rdweb, and implementing paymaster

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by 7-falseparfait** [comment]
Could I take over this issue?
I am a Front-end and Smart Contract Developer with expertise in Tailwind CSS, Next.js, TypeScript, JavaScript, and SQL. I am eager to contribute to this project and bring value with my skills.

**Comment by Holamite** [comment]
## About me
As someone who was previously a Stellar contract staff member and has worked on several Stellar projects, I have a solid understanding of the Stellar ecosystem and wallet integrations.

## How to tackle it!
For this task, I’ll make sure users can easily connect to their preferred Stellar wallets, specifically  Freighter. I’ll handle situations where a wallet isn’t installed by providing clear feedback to the user and following best practices to ensure the integration is secure and reliable.

I’ll also make sure the button fits perfectly with the application's theme, as outlined in the Figma design, and uses simple, clear text like “Connect Wallet” to make the user experience seamless.

## ETA
2-4hours

**Comment by OWK50GA** [comment]
May I handle this issue?
Hi, I'll like to take this issue.
Expect my first PR within 24 hours

**Comment by abdegenius** [comment]
Could I be assigned to this?

**Comment by vestor-dev** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by CollinsC1O** [comment]
Hello @KevinLatino I'm a front-end and a blockchain developer. I will love to work on this. Please assign

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 2-3 days.
Plan:
Analyze Wallet APIs: Research and integrate the APIs or SDKs for Stellar-compatible wallets (Albedo, Rabet, Freighter, and Xbull).

Implement Wallet Selection: Enhance ConnectWalletButton.tsx to allow users to select their preferred wallet using a dropdown or modal.

Detect Wallet Availability: Add logic to detect if the selected wallet is installed, and show clear error messages if not.

Handle Connections: Establish secure wallet connections using best practices for Stellar wallet integration, including handling authentication and account retrieval.

UI Design: Style the button and any additional UI elements (e.g., modals) to align with the Figma design and the application's theme. Use clear text such as “Connect Wallet.”

Testing: Test the integration thoroughly across all supported wallets to ensure seamless functionality and user experience.

Submit Deliverables: Ensure all code is clean, well-documented, and ready for review.

**Comment by chigozzdevv** [comment]
Can I try solving this issue?

**Comment by FrankiePower** [comment]
My name is Franklin Ejezie aka Super Franky, i am a frontend developer with 3 years experience and recently graduated from web3bridge africa, the premier and biggest blockhain developer community in africa. i am well equipped to build out the dashboard and also do blockchain integration with wagmi, ethersjs, appkit etc. i will start out with studying the figma file and can build out the UI in a day or two. if it requires blockchain integration to make the data dynanmic and the chart library it can take longer. so approximate time to project completion is 2-4 days.  make this a more generic template

**Comment by 3th-Enjay** [comment]
May I be assigned to this?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a front-end developer with experience in integrating various wallet providers for blockchain applications. I have worked with Stellar wallets in the past and am confident in my ability to implement the logic for the Connect Wallet button.

I will ensure that the button supports popular Stellar wallets such as Albedo, Rabet, Freighter, and Xbull, with functionality to detect and handle cases where a wallet is not installed. I will follow the Figma design and apply best practices for Stellar wallet integrations to ensure a seamless user experience.

Please assign me this task—I'm excited to contribute

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by Kachimercy1** [comment]
Can I start working on this?

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by ShantelPeters** [comment]
Could I try solving this?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by Nityam573** [comment]
Mind if I try this one?

**Comment by Villarley** [comment]
Hey @armandocodecr !
Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr
