### ISSUE TITLE
[FE]: Modify metada

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#26]
> [!IMPORTANT]
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Modify Metadata

## Description  
Update the application’s metadata in the `RootLayout` file, including the title and description for improved SEO. 

## Requirements  

1. **Update Metadata**:  
   - The current metadata is the default one generated when creating a new Next.js project. It needs to be updated as follows:  
     - Set the `title` to `"StarShop"`.  
     - Set the `description` to:  
       `"Empowering users to buy and sell unique digital assets on a blockchain-based marketplace, fostering transparency and trust through NFTs."`  

## Deliverables  
- Updated `metadata` constant in `RootLayout`.

**Comment by mimisavage** [comment]
I can handle this task, please kindly assign

**Comment by Luluameh** [comment]
Hi, I'm a frontend developer with strong experience in TypeScript and Next.js. I’ve carefully reviewed the Contributors Guide and the issue requirements.

 My  plan  on how to Solve the Issue:
Navigate to the RootLayout file in the Next.js project.
Update the metadata constant by replacing the default title with "StarShop".
Replace the description with: "Empowering users to buy and sell unique digital assets on a blockchain-based marketplace, fostering transparency and trust through NFTs."
Verify the changes by testing the metadata updates in the browser and inspecting SEO improvements.

Estimated Completion Time: 1 day

**Comment by josephchimebuka** [comment]
Can I take this issue?

**Comment by JosueBrenes** [comment]
## [FE]: Modify Metadata

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take less than 1 day to complete.

---

### Steps to Resolve

1. **Locate the RootLayout File**  
   - Navigate to the `src/app/layout.tsx` file where the metadata for the application is defined.

2. **Update Metadata**  
   - Modify the metadata constant to update the title and description:  
     - **Title:** "StarShop"  
     - **Description:** "Empowering users to buy and sell unique digital assets on a blockchain-based marketplace, fostering transparency and trust through NFTs."

3. **Test the Changes**  
   - Run the application and check the browser tab and page source to ensure the metadata is updated correctly.

4. **Finalize and Submit**  
   - Commit the changes to a branch named `feature/metadata-update`.  
   - Open a pull request with a summary of the implementation.

---

**Comment by Emmykeyz101** [comment]
I'd love to work on this!

**Comment by jpool09** [comment]
Hi team,
My name is Jean Pool Cruz, and I’m an experienced Developer with over 5 years of experience building web applications using technologies like React, TypeScript, and Tailwind CSS. I’ve worked extensively with component libraries and UI design, ensuring alignment with branding and accessibility standards, and I'm a Dojo Coding Member ⛩️

Plan to Solve the Issue:
1. Review Current Metadata:
    * Locate the RootLayout file and analyze the current metadata structure.
2. Update Metadata:
    * Update the title to "StarShop".
    * Replace the description with: "Empowering users to buy and sell unique digital assets on a blockchain-based marketplace, fostering transparency and trust through NFTs."
    * Ensure the updated metadata adheres to SEO best practices for improved search engine visibility.
3. Validate Changes:
    * Verify the metadata updates in the browser’s developer tools.
    * Test the application to confirm no unexpected issues arise from the changes.

Estimated Time of Completion (ETA): I estimate completing the task within half a day, ensuring the changes are properly tested.
Please let me know if there are additional details or requirements to consider. I’m excited to contribute to this project and look forward to your response!

Best regards, 
Jean Pool Cruz

**Comment by 7-falseparfait** [comment]
May I try my hand at this?

**Comment by Ekene001** [comment]
Hello I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

how I'll Tackle this task: 
I will begin by accessing the RootLayout file where the metadata is defined. I will modify the title and description fields to align with the desired SEO improvements, ensuring they are concise, relevant, and keyword-optimized. After making these updates, I will test the changes by rendering the application to verify that the metadata appears correctly in the browser and source code. Finally, I will validate the updates using SEO tools to ensure they meet best practices for search engine visibility.

ETA: 2days

**Comment by abdegenius** [comment]
May I pick this up?

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by starknetbrother** [comment]
Could I grab this task?

**Comment by Supa-mega** [comment]
I’m interested in this one.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by Kachimercy1** [comment]
I’m interested in this one.

**Comment by FrankiePower** [comment]
I am a frontend developer with over 3 years of experience, and I have recently graduated from Web3Bridge Africa, the premier and largest blockchain developer community in Africa. I am well-equipped to handle this task and can get it done inan hour.

**Comment by kayceeDev** [comment]
Can I take this issue?

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by accessing the Root Layout and editing the Meta data as specified. ETA 1 day

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies. My expertise includes: Nuxt.js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. I would love to contribute to this project.

How I plan on tackling this issue
My approach towards this issue after forking the repo and creating the branch I would work on, Would be to update the metadata in the RootLayout file in a Next.js project, I would locate the RootLayout File (RootLayout.tsx). I would then add the title and the description that was provided then save the file. ETA is 1hr.

**Comment by Prosper1218** [comment]
hello, I'm Prosper a frontend/Blockchain Developer. 
i'd like to fix this for you. 
Would take me few hours to fix.

**Comment by ShantelPeters** [comment]
Can I take this issue?

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by KevinLatino** [comment]
@Luluameh  Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr

**Comment by Luluameh** [comment]
Hi, I'm a frontend developer with strong experience in TypeScript and Next.js. I’ve carefully reviewed the Contributors Guide and the issue requirements.

 My  plan  on how to Solve the Issue:
Navigate to the RootLayout file in the Next.js project.
Update the metadata constant by replacing the default title with "StarShop".
Replace the description with: "Empowering users to buy and sell unique digital assets on a blockchain-based marketplace, fostering transparency and trust through NFTs."
Verify the changes by testing the metadata updates in the browser and inspecting SEO improvements.

Estimated Completion Time: 1 day

**Comment by BrunoAmbricca** [comment]
I will learn the existing code and research the best approach for this issue

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


I will set the title to "StarShop" and the description to "Empowering users to buy and sell unique digital assets on a blockchain-based marketplace, fostering transparency and trust through NFTs." Ensure that the metadata constant in the RootLayout file reflects these changes accurately, delivering the updated metadata as specified.

**Comment by Yunusabdul38** [comment]
Can I take care of this issue?

**Comment by Akanimorex** [comment]
My name is Akanimo Rex, and with my experience building frontend apps/dapps , I believe I am well capable to take this on.
The RootLayout file is where i'd set the title, description accordingly. I'd also make it in such a way the link appears as a preview when pasted on socials like twitter and telegram.

**Comment by Gifftybabe** [comment]
Hi! I'm Gift and I want to express my interest in the metadata modification task .
My Qualification Highlights
- Experienced in frontend development
- Familiar with metadata management
- Committed to following project contribution guidelines

My Proposed Approach
1. Carefully review existing metadata structure
2. Propose specific modification strategy
3. Implement changes with minimal disruption
4. Prepare comprehensive documentation of modifications

My Communication Plan
- Regular updates through pull request comments
- Open to feedback and collaborative refinement
- Committed to project's quality standards

I'm excited about the opportunity to contribute to StarShop-Frontend.
