### ISSUE TITLE
[FE]: Create Dashboard Page

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#29]
> [!IMPORTANT]
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

# Create Dashboard Page  

## Description  
Create the Dashboard page for the application, following the design specified in the provided Figma file. The page should include the necessary sections and components as outlined in the design, ensuring a clean and user-friendly interface.

## Requirements  

1. **Component Location**:  
   - The `Dashboard` route and component have been already created (the route is `/dashboard`, and the component is inside the `src/components/dashboard/DashboardComponent.tsx` folder).  
   - You just have to edit the `DashboardComponent.tsx` file.  

2. **Design**:  
   - Follow the layout and visual elements as per the Figma design for the Dashboard page, [Figma Design Link](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=pVTHQecm3MDfgGXN-0).  You have to use the `Dashboard` frame

# Image
<img width="875" alt="Captura de pantalla 2024-12-08 a las 7 46 27 p  m" src="https://github.com/user-attachments/assets/733f6f8c-1243-442d-9e7b-b00c42fe4f4e" />

### For the sale by month section, you need to create a chart using any type of chart library.

**Comment by ozo-vehe** [comment]
Estimated completion time: 1-3 days

To create the Dashboard page, I will:

1. Review the Figma design for the Dashboard page.
2. Edit the existing DashboardComponent.tsx file to match the design.
3. Implement the necessary sections and components as outlined in the design.
4. Ensure a clean and user-friendly interface.
5. Test the page for layout and visual consistency with the Figma design.

**Comment by NueloSE** [comment]
am a frontend developer with experience in developer friendly user applications 

Psuedo step to approach the above task

From my observation of  the Figma design I  understand the layout structure and required components for the dashboard.
- I'll break down the dashboard into logical sections (header, main content, sidebar) in my DashboardComponent.tsx file.
- I'll reuse any existing components we have in the codebase that match the Figma design elements.
- I'll implement the layout using Tailwind CSS grid/flexbox to match the design specifications.
- I'll organize component's state management for any dynamic dashboard elements.
- I'll ensure all spacing, colors, and typography match the Figma specifications exactly.
- I'll make the dashboard responsive if required by the design.
- I'll test the implementation against the Figma design for pixel-perfect accuracy.

**Comment by drakkomaximo** [comment]
Hi everyone!

I’d be happy to take on creating the Dashboard page. With over 5 years of experience in frontend development, I’ve worked on similar projects and can ensure a clean, user-friendly, and well-structured implementation.

Estimated time: 2-3 days

How I’ll approach it:

Use the existing route ("/dashboard") and edit the DashboardComponent.tsx file.
Follow the Figma design closely, ensuring the layout and visual elements match the Dashboard frame.
Deliver a polished and functional Dashboard page that aligns with the application’s branding.
Let me know if I can start working on this!

**Comment by mimisavage** [comment]
Can I try solving this issue?

**Comment by ozo-vehe** [comment]
Estimated completion time: 1-3 days

To create the Dashboard page, I will:

1. Review the Figma design for the Dashboard page.
2. Edit the existing DashboardComponent.tsx file to match the design.
3. Implement the necessary sections and components as outlined in the design.
4. Ensure a clean and user-friendly interface.
5. Test the page for layout and visual consistency with the Figma design.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by derianrddev** [comment]
Hello StarShop Team,

I am Derian Rodríguez, a member of the Dojo Coding community ⛩️💻. I’m excited to contribute to your Stellar-based project during the Only Dust Hackathon #11 🚀.

As a full-stack developer, I have experience in:

Frontend: JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
Backend: Node.js (Express.js, Nest.js).
Web3: Cairo.
Plan to Address the Issue
Edit the DashboardComponent.tsx file in src/components/dashboard/ and correctly configure the /dashboard route.
Apply the design based on the Figma scheme, incorporating images, icons, and text.
Ensure the page is fully responsive.
Here are my profiles:

GitHub
OnlyDust
Thank you for considering my application.

**Comment by emarc99** [comment]
I already have view access to your figma design, and will recreate the design by looking at properties of elements in figma, also 2 years experience developing pages with react vite, nextjs, tailwind and shadcn.

**Comment by Emmykeyz101** [comment]
Could I try solving this?

**Comment by Josue19-08** [comment]
Hi, I'm Josué, and I'm part of the Dojo Coding community. I have experience in programming languages such as Angular, React, Typescript, C#, .NET, C++, PHP, Python, Java, Node.js, and JavaScript, among others. I'm passionate about software development and enjoy contributing to open-source projects, applying my knowledge to solve problems in a practical way. Additionally, I’m working on the project Citizen Of Arcanis, where I’ve had to use Unity, so I’m also skilled with this tool.

I would like to work on this issue; I can complete it in 2 or 3 days.

I have worked on many pages similar to this one, so I am familiar with the topic. My approach is as follows: first, I will go to the path defined in the issue and analyze what elements are still needed for the page. Then, I will review the Figma design to start working on the structure of the layout. Finally, I will develop the page as expected in the design.

**Comment by zintarh** [comment]
Can I be assigned to this?

**Comment by 7-falseparfait** [comment]
Can I jump on this task?

**Comment by leevigh** [comment]
Hello StarShop Team! 

About Me  
I’m Levi, a frontend developer specializing in React and Next.js, with experience integrating blockchain-powered features through Solidity smart contracts.  

My Plan  
To solve this issue, I will:  
1. Create the strab, top products, store statistics, and sales per month components separately then add them to the DashboardComponent.tsx file accordingly, as shown in the design
2. Research the write chart type to use for displaying *sales per month* data and implement that. And since shadcn is among the tools used here, I'll implement the chart using that library 
3. Make the layout responsive to different screen sizes  

Estimated Time to Complete  
I estimate completing this task within 24-36 hours.  

Looking forward to your approval to contribute!

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by caxtonacollins** [comment]
Could I try solving this? ETA 24hrs

**Comment by abdegenius** [comment]
Is it okay if I take this?

**Comment by wheval** [comment]
Can I be assigned to this?
I would ensure it is a pixel perfect implementation of the Figma design.
ETA is 2 days.

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by chigozzdevv** [comment]
Can I be assigned to this?

**Comment by austineblaise** [comment]
How I Can Solve the Issue

I will create the Dashboard page by editing the DashboardComponent.tsx file, following the Figma design closely. I’ll ensure the layout and components match the design and include the "Sale by Month" chart using a suitable chart library. I will make sure the page is clean, user-friendly, and fully responsive.

**Comment by Cisco-A** [comment]
Can I attempt this issue?

**Comment by jedstroke** [comment]
I'd like to take this issue my ETA will be 3 days

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by fabrobles92** [comment]
Hello Fab here,

I work as a Full Stack using Python and JavaScript frameworks such as Plain React, Next and Vue where I have created several similar web pages, creating reusable component if necessary and following the styles defined by the UX team.

With that in mind I think this can be easily tackled by following the figma :)

**Comment by 3th-Enjay** [comment]
I'd like to handle this task.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by Supa-mega** [comment]
Can I be assigned to this?

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

##Solution Plan
After carefully going through the codebase on GitHub and the Figma design,
- I will write the code to Implement the Dashboard UI in the `DashboardComponent.tsx ` file.
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices

##ETA
3-4 Hours

**Comment by FrankiePower** [comment]
My name is Franklin Ejezie aka Super Franky, i am a frontend developer with 3+ years experience and recently graduated from web3bridge africa, the premier and biggest blockhain developer community in africa. i am well equipped to build out the dashboard and also do blockchain integration with wagmi, ethersjs, appkit etc. i will start out with studying the figma file and can build out the UI in a day or two. if it requires blockchain integration to make the data dynanmic and the chart library it can take longer. so approximate time to project completion is 2-4 days.

**Comment by Kachimercy1** [comment]
Mind if I take this issue?

**Comment by Levi-Ojukwu** [comment]
## About Me 
I am a web3 full stack developer with expertise in blockchain technology and frontend engineering. I build on EVM compatible (Solidity) and Starknet (Cairo) blockchains.
In the blockchain domain, my expertise in solidity and Cairo has enabled me to design, develop, and deploy smart contracts on the Ethereum and Starknet based platforms, facilitating decentralized applications (dApps) that are revolutionizing industries. 

## How to tackle this issue
- To tackle this issue, first I will have to study and understand the flow of the UI design.
- Then I will edit the `DashboardComponent.tsx` file and begin the development of the dashboard, getting the about your store, top products and your store statistics data from the database.
- While tackling this issue, I will make sure I follow best practice, and good naming convention.

## ETA - 4 - 5 max

**Comment by Kaminar-i** [comment]
Please i would like to work on this

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwind-css. I plan to approach this issue by building the "Dashboard" page by following the Figma design and also building the page to be mobile responsive. ETA 2 days

**Comment by ShantelPeters** [comment]
I'd love to work on this!

**Comment by Amarjeet325** [comment]
Could I be assigned to this?

**Comment by sonkeydotcom** [comment]
ETA less than 24hrs if I’m assigned to this. Permit me to e take this,

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation site.

I will interpret the design using any chart library for the end of the sale month by editing the dashboard.tsx file to the suitable one for the design.

Thanks, you will love to contribute to your project.

**Comment by stephanniegb** [comment]
Could I take on this issue? I have 3 years of experience building beautiful, performant and accessible user interfaces and I will do a great job at creating this dashboard page
Here is how i intend to go about the issue:
- i will inspect the figma design closely 
- i react the components making sure that i stick to the design (colors, sizes etc)
- i will make sure the components are responsive and looks great on all screen sizes
- i make sure all the components are accessible and sticks to the WCAG standards
- then I will test the UI and make sure it looks great on all screen sizes and across browsers. 

Here are some of my recent projects for your reference:                                                                                                - https://tba-frontend-eta.vercel.app 
- https://scroll-transform-recreate.vercel.app
- https://three-js-galaxy-silk.vercel.app/
