### ISSUE TITLE
[FE]: Create User Form (Step 1 of the Stepper)

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#30]
# [FE]: Create User Form (Step 1 of the Stepper)  

> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

## Description  
Implement the first step of the user registration using the design provided in the Figma file. This step is part of a multi-step form (Stepper) 

## Requirements  
1. **File to Edit**:  
   - Modify the file located at `src/components/register/steps/StepOneContent.tsx`.  

2. **Design**:  
   - Follow the Figma design exactly as provided to ensure consistency with the overall UI [Figma Design Link](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=pVTHQecm3MDfgGXN-0), you have to use the `User Form` section.  

   - Use proper styling techniques to maintain responsiveness and visual appeal.  

###  ⚠️ You don't have to create this, because it's already created
<img width="439" alt="Captura de pantalla 2024-12-09 a las 1 09 44 p  m" src="https://github.com/user-attachments/assets/7751ad0c-0a35-4e0d-b9f1-371ae9e0cc20" />

### You just have to create the form 
<img width="446" alt="Captura de pantalla 2024-12-09 a las 1 10 35 p  m" src="https://github.com/user-attachments/assets/20559c9b-4216-4f84-80ad-c2463bba3b02" />

**Comment by mymiracle0118** [comment]
I'd be happy to do this.

**Comment by ozo-vehe** [comment]
Is it okay if I take this?

**Comment by mimisavage** [comment]
Could I take over this issue?

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 1 day.
Plan:
Review Design: Thoroughly examine the Figma design for the User Form section to understand the layout and styling requirements.

Edit StepOneContent.tsx: Add the form fields and structure for the first step of registration, ensuring alignment with the design.

Form Fields: Implement the required input fields with appropriate validation logic to guide users.

Styling: Apply responsive and visually appealing styles using the project’s CSS framework (e.g., Tailwind CSS) to match the design.

Test: Verify the form’s functionality and appearance on various screen sizes and browsers, ensuring a smooth user experience.

Submit: Finalize the implementation, ensuring the code adheres to best practices, and submit for review.

**Comment by drakkomaximo** [comment]
Hello guys, I want to apply, to do all the forms:

Estimated time 1 to 3 days

Steps to get started:
1) Read the application description.
2) See the Figma design.
3) Create components according to the different parties involved.

Additional:

I will implement the React form hook because it is a great library for managing forms and zod schemas to improve validations.

**Comment by Luluameh** [comment]
I am a frontend developer with 3 years exprience in providing a clear and clean user interface for a better user exprience.
I have been working with Typescript, Javascript,Next. js and React.js.
My Overview of the task
I'm excited to contribute to implementing the first step of the user registration form. I understand the key requirements are:
- Modifying the `src/components/register/steps/StepOneContent.tsx` file
- Precisely following the Figma design for the User Form section
- Ensuring responsiveness and visual consistency

MY Proposed Approach to tackle the task
. Implement a clean, responsive form for the first registration step
. Use Tailwind CSS for styling to match the provided Figma design
. Ensure the form is pixel-perfect and responsive across different device sizes
. Focus on creating an intuitive user experience

**Comment by Agbeleshe** [comment]
**About me**
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

**My Approach in solving this issue**
Firstly, I will locate the StepOneContent.tsx component and then create a pixel-perfect design according to the Figma provided above.

**ETA**
My estimated time to complete this task is within 12hours - 24hours.

**Comment by josephchimebuka** [comment]
Mind if I take this issue?

**Comment by robertram** [comment]
Hi, I am from de Dojo Coding community and a new contributor to Only Dust. Im a web3 frontend developer and founder of a NFT ticketing platform. 
ETA: 2-3 days.
The way I will solve this is follow the styles guidelines to create a tailwind styling for the inputs. Then create the inputs and apply the classname to the inputs.

**Comment by JosueBrenes** [comment]
## [FE]: Create User Form (Step 1 of the Stepper)

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take 1 day to complete.

---

### Steps to Resolve

1. **Understand the Requirements**  
   - Review the Figma design to understand the structure and layout for the User Form section in Step 1 of the Stepper.  
   - Confirm the file `src/components/register/steps/StepOneContent.tsx` is already created and focus solely on implementing the form.

2. **Implement the Form**  
   - Navigate to `src/components/register/steps/StepOneContent.tsx`.  
   - Use the User Form section in the Figma design as a reference to create the form fields.  
   - Ensure all required fields, labels, and buttons match the design and maintain consistency with the application's overall styling.

3. **Styling and Responsiveness**  
   - Apply appropriate CSS or Tailwind CSS utilities to ensure the form is visually appealing and responsive across devices.

4. **Testing**  
   - Test the form for proper alignment, input validation, and visual consistency.  
   - Validate the integration of this form with the Stepper component for seamless navigation between steps.

5. **Finalize and Submit**  
   - Commit the changes to a branch named `feature/step1-user-form`.  
   - Open a pull request with details of the implementation.

---

**Comment by SYLVIANNORUKA** [comment]
Let me handle this issue!
I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by kcmikee** [comment]
I’d love to work on this task.

**Comment by zintarh** [comment]
I’d like to work on this.

**Comment by 7-falseparfait** [comment]
I’d love to work on this task.

I am a Front-end and Smart Contract Developer with expertise in Tailwind CSS, Next.js, TypeScript, JavaScript, and SQL. I am eager to contribute to this project and bring value with my skills.

**Comment by System625** [comment]
Hi! I'm Olamiposi, a frontend developer with experience in React, nextjs, TypeScript, and UI implementation. I've worked extensively with multi-step forms and component-based architecture.

Proposed Solution:
1. Implement StepOneContent.tsx using shadcn/ui components for consistent styling
2. Create form fields (name, email, password) with proper validation using react-hook-form
3. Add responsive styling using Tailwind CSS following the Figma specs
4. Implement password strength indicator and validation rules as shown in design
5. Add proper error handling and field validation messages
6. Ensure smooth integration with the parent Stepper component

ETA: 24 hours, including:
- 1-12 hours: Core implementation and form validation
- 12-18 hours: Styling and responsiveness
- 18-24 hours: Testing, refinements, and PR submission

I will make a draft PR within the first 12 hours

I've reviewed the Figma design thoroughly and can match the UI precisely. I'm comfortable with the tech stack and can start immediately.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Ekene001** [comment]
I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

how I'll tackle this task:
I will start by reviewing the Figma design to ensure I understand all the elements, like input fields, buttons, and their layout. I will then code the step to match the design, ensuring it integrates smoothly with the multi-step form (Stepper). I’ll add any necessary input validation to ensure users can only proceed when the required fields are completed correctly. Once done, I’ll test it to confirm it works as expected and looks consistent with the design. Finally, I’ll review it against the Figma file to make sure everything is accurate before moving forward.

ETA: 2 days

**Comment by abdegenius** [comment]
Can I work on this, please?

**Comment by derianrddev** [comment]
**Hello StarShop Team,**

I am **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your **Stellar**-based project during the **Only Dust Hackathon #11** 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to Address the *Issue* **"Implement the First Step of User Registration"**

1. Edit the `StepOneContent.tsx` file located in `src/components/register/steps/`.
2. Implement the form following the exact design of the *User Form* section in the Figma file.
3. Ensure proper styling to maintain visual consistency, responsiveness, and usability.
4. Test the form to ensure it works correctly as part of the registration flow.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by austineblaise** [comment]
**How I Can Solve the Issue**

I will create the user form for Step 1 in `StepOneContent.tsx` by following the Figma design. I’ll make sure the form is responsive, visually appealing, and works well with the rest of the project.

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 1 day.
Plan:
Review Design: Thoroughly examine the Figma design for the User Form section to understand the layout and styling requirements.

Edit StepOneContent.tsx: Add the form fields and structure for the first step of registration, ensuring alignment with the design.

Form Fields: Implement the required input fields with appropriate validation logic to guide users.

Styling: Apply responsive and visually appealing styles using the project’s CSS framework (e.g., Tailwind CSS) to match the design.

Test: Verify the form’s functionality and appearance on various screen sizes and browsers, ensuring a smooth user experience.

Submit: Finalize the implementation, ensuring the code adheres to best practices, and submit for review.

**Comment by jedstroke** [comment]
I'd like to take this issue my ETA will be 3 days

**Comment by 3th-Enjay** [comment]
Can I take care of this issue?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a front-end developer with experience in building responsive forms and UI components. I have a strong focus on creating user-friendly interfaces that are consistent with design systems, ensuring both functionality and visual appeal.

I would love to implement the first step of the user registration form as part of a multi-step process, following the Figma design provided. With my experience in working with React components and maintaining design consistency, I am confident I can complete this task effectively. Please assign me this task—I look forward to contributing to the project!

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by Supa-mega** [comment]
Can I handle this task?

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by Kachimercy1** [comment]
I'd like to handle this task.

**Comment by kayceeDev** [comment]
I’m interested in this one.

**Comment by therealemino** [comment]
I'd be happy to do this.

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by building the "User form " component to be responsive, following the design. ETA 2 days

**Comment by ryzen-xp** [comment]
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to various projects like Chainevents and Arkprojects.
I will implement the first step of the user registration form using the design provided in the Figma file. I will ensure the form follows the exact styling and structure as required and maintain responsiveness for a seamless user experience. Please assign this issue to me.

Thank you!

**Comment by ShantelPeters** [comment]
Can I take this issue?

**Comment by Amarjeet325** [comment]
Can I tackle this one?

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I will interpret the design using my front-end skills by making use of the font and any other image or icon used in the design and make it responsive for all devices.

thanks will love to contribute to this project

**Comment by Gladchux14** [comment]
hello! my name is Gladchux.
I have extensively used JavaScript and typescript to deliver quality and responsive interactive projects.

My plan to resolve this issue:
create a branch after cloning the repository.
Study the codebase to understand it.
locate the stepOne content file.
build/ design form fields according to figma file.
ensure the form validation.
implement styling from the design.
ensure responsiveness for all screen sizes.
raise an explicit PR and notify maintainers.

my ETA for this would be 26 hrs.

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer with strong foundation in modern web development frameworks and technologies. My expertise includes: Nuxt.js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. 
I would love to contribute to this project. My approach towards this issue after forking the repo and creating a new branch . I would then locate the file in src/components/register/steps/StepOneContent.tsx . I would then import the logo. I would also export the needed asserts(like icons, and image and background Image). After setting the image as the background. I would create a main div which I would centre. I would then import the needed elements and style the form with tailwindss to fit the design

**Comment by Nityam573** [comment]
May I be assigned to this?

**Comment by morelucks** [comment]
My name is Kamshak Lucky Isuwa, and I am thrilled to apply for the frontend developer role to implement Step 1 of the User Form as part of the multi-step registration process. With extensive experience in React.js, Next.js, and form handling libraries like Formik and React Hook Form, I am confident in delivering a responsive and user-friendly component within 24 hours, strictly adhering to the Figma design.

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
Firstly, I will locate the StepOneContent.tsx component and then create a pixel-perfect design according to the Figma provided above.

ETA
My estimated time to complete this task is within 12hours - 24hours.

**Comment by Luluameh** [comment]
I am a frontend developer with 3 years exprience in providing a clear and clean user interface for a better user exprience.
I have been working with Typescript, Javascript,Next. js and React.js.
My Overview of the task
I'm excited to contribute to implementing the first step of the user registration form. I understand the key requirements are:

Modifying the src/components/register/steps/StepOneContent.tsx file
Precisely following the Figma design for the User Form section
Ensuring responsiveness and visual consistency
MY Proposed Approach to tackle the task
. Implement a clean, responsive form for the first registration step
. Use Tailwind CSS for styling to match the provided Figma design
. Ensure the form is pixel-perfect and responsive across different device sizes
. Focus on creating an intuitive user experience

Estimated Completion Time: 2 days

**Comment by BrunoAmbricca** [comment]
I will learn the existing code and research the best approach for this issue

**Comment by brolag** [comment]
I have over 10 years of experience working with web technologies. My plan is to create new reusable components if required and then implement the step-by-step wizard.
I've worked in similar tasks in the past, the most recent one was this one: https://github.com/safetrustcr/Frontend/issues/68

**Comment by portableDD** [comment]
Hi, i am Emmanuel Dorcas and i like to tackle this issues
I'm a frontend developer with experience using React, Next.js and TypeScript and I'm also skilled at creating intuitive and responsive user interfaces, ensuring a seamless experience for users.

how I will tackle this is
I will create the form, taking in three input filed for username, email and location, inserting the icons from react icon.
using tailwind CSS to make it visual appealing

Thanks

**Comment by JosueBrenes** [comment]
## [FE]: Create User Form (Step 1 of the Stepper)

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take 1 day to complete.

---

### Steps to Resolve

1. **Understand the Requirements**  
   - Review the Figma design to understand the structure and layout for the User Form section in Step 1 of the Stepper.  
   - Confirm the file `src/components/register/steps/StepOneContent.tsx` is already created and focus solely on implementing the form.

2. **Implement the Form**  
   - Navigate to `src/components/register/steps/StepOneContent.tsx`.  
   - Use the User Form section in the Figma design as a reference to create the form fields.  
   - Ensure all required fields, labels, and buttons match the design and maintain consistency with the application's overall styling.

3. **Styling and Responsiveness**  
   - Apply appropriate CSS or Tailwind CSS utilities to ensure the form is visually appealing and responsive across devices.

4. **Testing**  
   - Test the form for proper alignment, input validation, and visual consistency.  
   - Validate the integration of this form with the Stepper component for seamless navigation between steps.

5. **Finalize and Submit**  
   - Commit the changes to a branch named `feature/step1-user-form`.  
   - Open a pull request with details of the implementation.

---
