### ISSUE TITLE
[FE]: Create Store Form (Step 3 of the Stepper)

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#31]
# [FE]: Create Store Form (Step 3 of the Stepper)  

> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

## Description  
Implement the third step of the store registration using the design provided in the Figma file. This step is part of a multi-step form (Stepper) and should strictly adhere to the specified layout and style.  

## Requirements  
1. **File to Edit**:  
   - Modify the file located at `src/components/register/steps/ThreeStepContent.tsx`.  

2. **Design**:  
   - Follow the Figma design exactly as provided to ensure consistency with the overall UI [Figma Design Link](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=pVTHQecm3MDfgGXN-0), you have to use the `Store Form` Section.  
   - Use proper styling techniques to maintain responsiveness and visual appeal.  

###  ⚠️ You don't have to create this, because it's already created
<img width="439" alt="Captura de pantalla 2024-12-09 a las 1 09 44 p  m" src="https://github.com/user-attachments/assets/16c696f8-8c89-432b-b7b0-398d1e448873" />

### You just have to create the form 
<img width="370" alt="Captura de pantalla 2024-12-09 a las 1 27 07 p  m" src="https://github.com/user-attachments/assets/b8307948-5c28-47aa-a9d1-cd008ba7e280" />

**Comment by mymiracle0118** [comment]
May I try my hand at this?

**Comment by ozo-vehe** [comment]
Could I take over this issue?

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by drakkomaximo** [comment]
Hello guys, I want to apply, to do all the forms:

Estimated time 1 to 3 days

Steps to get started:

Read the application description.
See the Figma design.
Create components according to the different parties involved.
Additional:

I will implement the React form hook because it is a great library for managing forms and zod schemas to improve validations.

**Comment by LawalRahman** [comment]
Can I jump on this task?

**Comment by Agbeleshe** [comment]
**About me**
I am a frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

**My Approach in solving this issue**
First off I will locate the ThreeStepContent.tsx component and then create a pixel-perfect design according to the figma provided above.

**ETA**
My estimated time to complete this task is within 12mins - 24hours.

**Comment by Agbeleshe** [comment]
**About me**
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

**My Approach in solving this issue**
Firstly, I will locate the ThreeStepContent.tsx component and then create a pixel-perfect design according to the Figma provided above.

**ETA**
My estimated time to complete this task is within 12hours - 24hours.

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
I break down my approach to this two basic steps:
Step one: I will locate the ThreeStepContent.tsx component
Step two: I will then create a pixel-perfect design according to the Figma provided above. (which involve implementing designs and functions like form validation if required)

ETA
My estimated time to complete this task is within 12hours - 24hours.

**Comment by josephchimebuka** [comment]
May I pick this up?

**Comment by JosueBrenes** [comment]
## [FE]: Create Store Form (Step 3 of the Stepper)

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take 1 day to complete.

---

### Steps to Resolve

1. **Understand the Requirements**  
   - Review the Figma design to ensure a clear understanding of the form structure and layout for Step 3 of the Stepper.  
   - Note that the file `src/components/register/steps/ThreeStepContent.tsx` already exists, and only the form needs to be created within it.

2. **Implement the Form**  
   - Navigate to `src/components/register/steps/ThreeStepContent.tsx`.  
   - Use the "Store Form Section" from the Figma design as a reference to create the form fields.  
   - Ensure the layout, styling, and field components match the design specifications.

3. **Maintain Responsiveness**  
   - Use proper CSS or Tailwind CSS utilities to ensure the form is responsive across all screen sizes.

4. **Testing**  
   - Validate the form fields for alignment, styling, and functionality.  
   - Test the integration of this step with the Stepper component to ensure smooth navigation between steps.

5. **Finalize and Submit**  
   - Commit the changes to a branch named `feature/step3-store-form`.  
   - Open a pull request with details of the implementation.

---

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 2days.

**Comment by 7-falseparfait** [comment]
Can I be assigned to this?

I am a Front-end and Smart Contract Developer with expertise in Tailwind CSS, Next.js, TypeScript, and JavaScript. I am eager to contribute to this project and bring value with my skills.

**Comment by Emmykeyz101** [comment]
I'd like to handle this task.

**Comment by Emmanex01** [comment]
Can I start working on this?

**Comment by Ekene001** [comment]
I'm Ekene, a frontend and blockchain developer with proficiency is Rust, React, Solidity, and typescript, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table.
please can i be assigned to this task?

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a smart contract developer with experience in both backend and frontend development. After completing the Cairo Basecamp, I gained a strong understanding of decentralized applications and contributed to several projects on OnlyDust, focusing on UI optimization and smart contract development.

I would love to contribute to implementing the third step of the store registration form. With my experience in frontend development and attention to detail, I can ensure the design is accurately followed, maintaining responsiveness and consistency with the provided Figma layout. I’m confident I can handle this task and ensure a smooth integration of the form step into the multi-step process. Please assign me this task—I look forward to contributing to the project!

ETA 1 DAY

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by austineblaise** [comment]
**How I Can Solve the Issue**

As a frontend/JavaScript blockchain developer, I will create the store form for Step 3 in `ThreeStepContent.tsx`. I will follow the Figma design closely to make sure the form looks exactly as required. I will ensure the form is responsive and visually appealing while keeping the code clean and consistent with the rest of the project.

**Comment by abdegenius** [comment]
Can I take this issue?

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by derianrddev** [comment]
**Hello StarShop Team,**

I am **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your **Stellar**-based project during the **Only Dust Hackathon #11** 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to Address the *Issue*

1. Edit the `ThreeStepContent.tsx` file located in `src/components/register/steps/`.
2. Implement the form following the exact design of the *Store Form* section in the Figma file.
3. Apply proper styling to ensure visual consistency, responsiveness, and visual appeal.
4. Validate the functionality of the form and its integration within the registration flow.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by Cisco-A** [comment]
Let me handle this issue!

**Comment by jedstroke** [comment]
I'd like to take this issue my ETA will be 3 days

**Comment by 3th-Enjay** [comment]
May I handle this issue?

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by Supa-mega** [comment]
Can I jump on this task?

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by Kachimercy1** [comment]
Would love to tackle this!

**Comment by kayceeDev** [comment]
Could I be assigned to this?

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by mariocodecr** [comment]
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.


To complete this task, implement the third step of the store registration form within the multi-step form (Stepper) by editing the file located at src/components/register/steps/ThreeStepContent.tsx. Follow the Figma design precisely, focusing on the Store Form Section, to ensure visual and functional consistency with the overall UI. The primary task is to create the form fields as specified in the design, ensuring responsiveness and styling align with the project's existing standards. Since the step itself is already created, only the form needs to be developed. Properly structured and styled code will maintain a cohesive and visually appealing user experience.

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by Amarjeet325** [comment]
Could I be assigned to this?

**Comment by Gladchux14** [comment]
Chello! my name is Gladchux.
I have extensively used JavaScript and typescript to deliver quality and responsive interactive projects.

My plan to resolve this issue:
create a branch after cloning the repository.
Study the codebase to understand it.
locate the threeStepContent file.
build/design form fields according to the figma file design.
ensure necessary validation for the fields.
ensure design consistency.
ensure responsiveness for all screen sizes.
raise an explicit PR and notify maintainers.

my ETA for this would be 26hrs.

**Comment by KevinLatino** [comment]
@Akshola00  Task assigned to you. Let me know if you need further clarification or additional support!😊

Here is our telegram group, please join https://t.me/starshopcr

**Comment by Akshola00** [comment]
@KevinLatino on it now

**Comment by KevinLatino** [comment]
please @Akshola00, follow the step one content styles, i have alrady merged it, and i think you can follow the styles
