### ISSUE TITLE
 [FE]: Create Loading Spinner

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#32]
# [FE]: Create Loading Spinner  

> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

## Description  
Create a simple and visually appealing loading spinner component. The spinner should use a purple color to align with the application's branding.  

## Requirements  

1. **File to Edit**:  
   - Modify the file located at `src/components/ui/LoadingSpinner.tsx`.  

2. **Implementation**:  
   - You can use this code if you want to:  
     ```tsx  
     export const MainSpinner = () => (  
       <div className={`w-5 h-5 border-4 border-t-4 border-t-transparent border-light-blue rounded-full animate-spin`}></div>  
     );  
     ```  
   - Replace `border-light-blue` with a suitable purple color, e.g., `border-purple-500` using Tailwind CSS.  
   - The implementation of that code is optional, you can create other loading spinner if you want to!

**Comment by mymiracle0118** [comment]
Can I attempt this issue?

**Comment by ozo-vehe** [comment]
Can I be assigned to this?

**Comment by mimisavage** [comment]
Could I grab this task?

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within less than 2 hours,

Plan:
Design and Branding: Ensure the spinner matches the application's branding by using a purple color (border-purple-500 or similar) as specified.

Modify the Component: Update or create the LoadingSpinner.tsx file. I will refine the provided implementation or design a custom spinner while ensuring simplicity and smooth animations.

Responsive Styling: ensure the spinner adapts well to different contexts, maintaining a professional and visually appealing look.

Testing: Verify the spinner displays correctly and performs smoothly across different browsers and screen sizes.

Submit: Ensure code quality aligns with the contribution guide before submitting for review.

**Comment by LawalRahman** [comment]
May I try my hand at this?

**Comment by NueloSE** [comment]
Am a frontend developer with experience in using Js, typescript and other frontend framework

Psuedo step to solving the above task:

- I will open src/components/ui/LoadingSpinner.tsx for modification.
- I will either use the provided spinner code and simply change border-light-blue to border-purple-500, or create your own spinner design.
- Using the provided code, the component creates a circular spinner using border properties and Tailwind's animate-spin.
- Or i could create my own, ensure it's visually appealing and uses purple colors from Tailwind's palette to match branding.
- I'll Keep the component simple and focused on just the loading animation functionality.
- I will test the spinner to ensure smooth animation and correct purple coloring.
- finaly I will export the component properly so it can be imported and used throughout the application.

**Comment by Luluameh** [comment]
I am a frontend developer with 3 years exprience in providing a clear and clean user interface for a better user exprience.
I have been working with Typescript, Javascript, and React.js.
HOW I WILL APPROACH THE ISSUE
After carefully reviewing  the Contributors Guide to ensure that  I follow all project guidelines
I plan to:
 - Implement a clean, responsive loading spinner component
-  Use Tailwind CSS for styling, specifically utilizing a purple color palette
- Ensure the spinner is simple yet visually appealing and  Add appropriate comments and follow the project's coding standards

**Comment by Agbeleshe** [comment]
@KevinLatino Hello,

**About me**
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

**My Approach in solving this issue**
I plan to update the `LoadingSpinner.tsx` component file by either modifying the current design above or creating a fresh design. The current spinner can be customized by changing `border-light-blue` to `border-purple-500`. I will ensure the design is not complex and beautiful. Once finalized, I'll test it thoroughly and ensure it’s exported correctly for use across the application.

**ETA**
My estimated time to complete this task is within 30mins - 12hours.

**Comment by Agbeleshe** [comment]
**About me**
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

**My Approach in solving this issue**
I plan to update the `LoadingSpinner.tsx` component file by either modifying the current design above or creating a fresh design. The current spinner can be customized by changing `border-light-blue` to `border-purple-500`. I will ensure the design is not complex and beautiful. Once finalized, I'll test it thoroughly and ensure it’s exported correctly for use across the application.

**ETA**
My estimated time to complete this task is within 30mins - 12hours.

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
I plan to update the `LoadingSpinner.tsx` component file by either modifying the current design above or creating a fresh design. The current spinner can be customized by changing `border-light-blue` to `border-purple-500`. I will ensure the design is not complex and beautiful. Once finalized, I'll test it thoroughly and ensure it’s exported correctly for use across the application.

ETA
My estimated time to complete this task is within 30mins - 12hours.

**Comment by josephchimebuka** [comment]
Can I take care of this issue?

**Comment by Steph3097** [comment]
Hi! Im Sttef,
I’m part of Dojo Coding and I’m excited to help design and implement a loading spinner. I have experience in front-end development and a strong eye for design, 
Here’s how I’ll approach the task:
- I’ll create a loading spinner that matches the application's branding by incorporating a purple color
- Check that everything works as expected .
I’m looking forward to contributing to this task! Thank you for considering my application.

**Comment by JosueBrenes** [comment]
## [FE]: Create Loading Spinner

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take 1 day to complete.

---

### Steps to Resolve

1. **Review Requirements**  
   - Understand the application's branding to select the appropriate shade of purple.  
   - Review the suggested code snippet to determine if it fits the requirements or if a custom implementation would be better.

2. **Edit the File**  
   - Navigate to `src/components/ui/LoadingSpinner.tsx`.  
   - Implement the spinner using Tailwind CSS. I will use the class `border-purple-500` or a similar purple tone to ensure branding consistency.

3. **Custom Implementation (if needed)**  
   - If the suggested snippet doesn't align with the design requirements or application needs, I'll create a custom spinner.  
   - The custom spinner will be visually appealing and lightweight, ensuring compatibility across devices.

4. **Testing**  
   - Verify the spinner's appearance in different scenarios and sizes.  
   - Ensure smooth animations and consistent performance.

5. **Finalize and Document**  
   - Confirm that the spinner meets the design and functional expectations.  
   - Commit the changes to a branch named `feature/loading-spinner`.  
   - Open a pull request with details of the implementation.

---

**Comment by Emmanex01** [comment]
Can I start working on this?

**Comment by jpool09** [comment]
Hi team,
My name is Jean Pool Cruz, and I’m an experienced Developer with over 5 years of experience building web applications using technologies like React, TypeScript, and Tailwind CSS. I’ve worked extensively with component libraries and UI design, ensuring alignment with branding and accessibility standards, and I'm a Dojo Coding Member ⛩️

Plan to Solve the Issue:
1. Understand Requirements: Carefully review the Contributor’s Guide and the project’s design system to ensure compliance with the branding guidelines.
2. Develop Component:
    * Create the LoadingSpinner component in src/components/ui/LoadingSpinner.tsx.
    * Implement the provided example spinner using Tailwind CSS, replacing the color with border-purple-500 to match the branding.
    * Ensure the component supports customization if needed (e.g., size, speed).
3. Test: Test the spinner visually and ensure it performs well across different browsers and screen sizes.
4. Documentation: Update any relevant documentation or add comments to the code to ensure future maintainability.

Estimated Time of Completion (ETA): I estimate completing the task within half a day, or at most one day, allowing enough time for testing and addressing any feedback if needed.
Please let me know if there’s anything else I should consider before starting. I’m excited to contribute and look forward to your response!

Best regards, Jean Pool Cruz

**Comment by kcmikee** [comment]
I'd love to give this a go.
Im a frontend engineer with 4years of experience

**Comment by Emmykeyz101** [comment]
Can I tackle this one?

**Comment by emarc99** [comment]
I recently developed a web app using nextjs for frontend of a dApp, also have experience with ReactJs, Vite and Tailwind. I did this spinner for for an MSME hackathon last month. 
ETA- 1day

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a smart contract developer specializing in StarkNet and Cairo, with experience in frontend development. After completing the Cairo Basecamp, I gained a solid understanding of decentralized applications and contributed to several projects on OnlyDust, focusing on both smart contract development and UI optimization.

I would love to take on the task of creating the loading spinner component. With my experience using Tailwind CSS and frontend development, I can implement a visually appealing and functional spinner that aligns with the purple branding of the application. I’m confident in delivering a smooth and efficient solution for this task, either by adapting the provided code or creating a custom spinner. Please assign me this task—I’m excited to contribute to the project!
ETA 1 DAY

**Comment by 7-falseparfait** [comment]
I'd love to work on this!

I am a Front-end and Smart Contract Developer with expertise in Tailwind CSS, Next.js, TypeScript, JavaScript, and SQL. I am eager to contribute to this project and bring value with my skills.

**Comment by Prosper1218** [comment]
Hello, I'm prosper. I'm a frontend/Blockchain developer with years of experience. 
If this issue is assigned to me, I'll : 
-review the UI and draft out a better and suitable loading spinner.
-Ensure the spinner retains perfect size and is well aligned in all screen.
This will take me a maximum of 2 days to achieve. 
Assign this issue to me and let me do what I do best.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by austineblaise** [comment]
**How I Can Solve the Issue**  

As a frontend/JavaScript blockchain developer, I will create a responsive and visually appealing loading spinner in `LoadingSpinner.tsx`. Using Tailwind CSS, I’ll ensure the spinner matches the application’s branding with the purple color (`border-purple-500`). I’ll either enhance the provided code or create a custom solution that’s clean, efficient, and consistent with the Contributors Guide.

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

I am a fullstack and blockchain developer having experience for more than 1.5 years and had worked on many projects from previous odhack my profile: (https://app.onlydust.com/u/SudiptaPaul-31)

**Comment by System625** [comment]
Hi! I'm Olamiposi, a frontend developer with experience in React and UI component development. I specialize in creating reusable, accessible UI components and have implemented various loading indicators in production applications.

Proposed Solution:
1. Create a customizable LoadingSpinner component with size and color props
2. Implement smooth CSS animations using Tailwind's animate utilities
3. Add ARIA attributes for accessibility (aria-busy, role="status")
4. Create size variants (sm, md, lg) for flexibility
5. Add optional fade-in animation to prevent flash on quick loads
6. Include documentation and usage examples

ETA: 3-8 hours, including:
- 1-3 hours: Component implementation and animation
- 1-2 hours: Testing across different sizes/contexts
- 1-3 hours: Documentation and PR submission

I can enhance the provided code with better accessibility and customization options while maintaining the project's purple branding.

**Comment by caxtonacollins** [comment]
May I take care of this?

**Comment by abdegenius** [comment]
Can I handle this task?

**Comment by vestor-dev** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within less than 2 hours,

Plan:
Design and Branding: Ensure the spinner matches the application's branding by using a purple color (border-purple-500 or similar) as specified.

Modify the Component: Update or create the LoadingSpinner.tsx file. I will refine the provided implementation or design a custom spinner while ensuring simplicity and smooth animations.

Responsive Styling: ensure the spinner adapts well to different contexts, maintaining a professional and visually appealing look.

Testing: Verify the spinner displays correctly and performs smoothly across different browsers and screen sizes.

Submit: Ensure code quality aligns with the contribution guide before submitting for review.

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by chigozzdevv** [comment]
May I pick this up?

**Comment by jedstroke** [comment]
I'd like to take this issue my ETA will be 3 days

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by wheval** [comment]
Hello, I'd love to give this a go.
I'm an experienced frontend developer.
I would modify the LoadingSpinner.tsx file using the provided starter code and further enhance the code appropriately. I would ensure it aligns with the brand's color.
I would also ensure it displays on loading state.

ETA is 1 day.

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub and the Figma design,
- I will write the code to Modify the LandingPage UI in the `LoadingSpinner.tsx `file.
- I will create a sleek and unique spinner following the project brand color theme
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the spinner is responsive and works across all devices

## ETA
2-4 Hours

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Kachimercy1** [comment]
Could I take over this issue?

**Comment by therealemino** [comment]
Hi, I've got over 4 years hands on experience working on frontend web applications (React, Vue, Next, Nuxt). I've gone through the repository and Figma designs. Can I handle this task?

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by building the "Spinner" component to be responsive. ETA 1 day

**Comment by trashcancries** [comment]
i am a frotend developer with 2 years of experience in react.

i will modify the loadingspinner.tsx file to create a new spinner which can be used across the entire codebase, and make sure everything is working as expected.

eta: 2 days

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by blessingbytes** [comment]
I would love to fix this issue

**Comment by omsant02** [comment]
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Winner in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer


My approach to solve this issue is by modifying the ui/LoadingSpinner.tsx that is already there in component folder,
would use react Loader for the animation and will stick to the color that aligns with the application branding

ETA : 12hrs

**Comment by ShantelPeters** [comment]
Can I take this issue?

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 2+ years of experience and I have worked with frontend technologies like React, NextJS, Javascript/Typescript. I'm a recent graduate of the Web3bridge Africa the foremost and premier blockchain developer community. I have made contributions in many open source projects and i look forward to contributing to this. My approach to this will be to

1- Review the project structure, figma link and necessary files 
2- Implement the Loading Spinner with the proper color scheme to align with the application's branding.

ET: 1 day

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

To solve this issue, I’ll take the following steps:
1.⁠ ⁠I’ll use the pre-existing component src/components/landing-page/LandingComponent.tsx and ensure the route / is correctly configured in your my routing.
2.⁠ ⁠⁠I’ll make reference to the already Figma design to structure the page into sections like header, features, CTA, and footer.  I’ll break the design into components (e.g., Header, FeaturesSection, CTAButton, Footer). I’ll use layout techniques like Flexbox or CSS Grid for alignment
3.⁠ ⁠⁠I’ll implement media queries or CSS-in-JS (e.g., styled-components) for mobile-first design and ensure the page adapts correctly on all screen sizes.
4.⁠ ⁠⁠I’ll use semantic HTML elements for better structure and accessibility and include necessary aria attributes for accessibility.
5.⁠ ⁠⁠Lastly, I’ll test to verify the design and functionality across devices and screen sizes and ensure interactive elements (buttons, links) work as expected.

ETA: 2 days MAX
Kindly assign me please, I’m ready to work.

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites. 

I will modify the file located at src/components/ui/LoadingSpinner.tsx  which adhere to the brand, using the code above or any other loading spinner.

thanks will love to contribute to this project.
