### ISSUE TITLE
[FE]: Create Settings Page

### ISSUE THREAD

**Issue by KevinLatino** [StarShopCr/StarShop-Frontend#33]
# [FE]: Create Settings Page  

> [!IMPORTANT]  
Before applying, please read the [Contributors Guide](https://github.com/StarShopCr/contributors-guide). Following the guide increases your chances of being assigned to this task.  

## Description  
Implement the Settings page for the application. The route `/settings` is already configured, and the task involves creating the page using the specified component file. The design is already available in Figma and should be followed strictly.  

## Requirements  

1. **File to Edit**:  
   - Use the component located at `src/components/settings/SettingsComponent.tsx` to implement the Settings Page.  

2. **Design**:  
   - Follow the design provided in Figma: [Figma Design Link](https://www.figma.com/design/OsBwtlrTh74tPs3S3MZm1N/StarShop-Figma?node-id=0-1&node-type=canvas&t=pVTHQecm3MDfgGXN-0).  

## Image
<img width="994" alt="Captura de pantalla 2024-12-10 a las 12 52 08 p  m" src="https://github.com/user-attachments/assets/0d0dc4fc-69ac-4fa5-9d56-9178c374f23c" />

## For this section: 
<img width="150" alt="Captura de pantalla 2024-12-10 a las 3 09 38 p  m" src="https://github.com/user-attachments/assets/56078087-3382-4a47-bb6c-6af0c6787d50" />

Please use the component: `src//components/ui/UploadPhotoProfile.tsx`

**Comment by mymiracle0118** [comment]
Could I take on this issue?

**Comment by ozo-vehe** [comment]
Can I work on this, please?

**Comment by mimisavage** [comment]
Could I grab this task?

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 2 days.

Plan:
Understand Design Requirements: Review the Figma design thoroughly to ensure accurate implementation.

Set Up Layout: Begin by structuring the SettingsComponent.tsx to match the layout in the Figma design 

Styling: styled the components to adhere strictly to the design guidelines. and ensuring responsiveness and accessibility.

Test: Validate the page functionality and appearance across different devices and browsers.

Submit for Review: Ensure the implementation meets all requirements before creating a pull request.

**Comment by jahrulezfrancis** [comment]
I’m a full-stack Web & Mobile App engineer with 4+ years of experience building responsive applications using React, React Native, Node.js, and TypeScript. I’ll create the Settings Page in SettingsComponent.tsx by following the Figma design closely, reusing components, and ensuring responsiveness. Once complete, I’ll test thoroughly to ensure everything works perfectly.
ETA: Within 24 hours.

**Comment by LawalRahman** [comment]
May I pick this up?

**Comment by Jethrolopwus** [comment]
Hi, I'm a front end developer with proficiency in JavaScript, Reacts, Next.js and typescript. I will want to implement this setting page and ensure is responsive on all screen sizes using tailwind css and the ETA is 2days.

**Comment by Agbeleshe** [comment]
@KevinLatino Hello,

**About me**
 I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript.  And for styling tailwindCss,  Vanila CSS,  SCSS,  mantime, etc.

**My Approach in solving this issue**
I will first tackle this issue by analyzing the figma file that is provided above and locating the "SettingsComponent.tsx" , where I will implement the styling for the settings page according to the figma page.

**ETA**
Design implementation will be done within 12-24 hours if I am assigned this task.

**Comment by Agbeleshe** [comment]
About me
I am a diligent frontend developer with more than 3 years of working experience in creating responsive, pixel-perfect web and mobile applications with various libraries and frameworks, especially React, Next.Js, TypeScript. And for styling tailwindCss, Vanila CSS, SCSS, mantime, etc.

My Approach in solving this issue
I will first tackle this issue by analyzing the figma file that is provided above and locating the "SettingsComponent.tsx" , where I will implement the styling for the settings page according to the figma page.

ETA
My estimated time to complete this task is within 12-24 hours.

**Comment by Holamite** [comment]
Could I take a shot at this?

## About Me
I’m passionate about making Web3 technology more accessible because I believe user experience is one of the biggest barriers to bringing new users into the decentralized world. That’s why I focus on creating user-friendly applications.

## Solution plan
I’ll start by carefully reviewing the Figma design to fully understand the flow and design details. I’ll use the existing route  Settings.tsx to keep the implementation clean. My goal will be to create a responsive layout that looks great and works smoothly on any device. Once the design is implemented, I’ll test it thoroughly to make sure it’s functional, polished, and ready to go.

2-4 hours to complete

**Comment by Ayoazeez26** [comment]
I am a software developer with over 5 years experience building applications. I intend on tackling this issue by modifying the SettingsComponent.tsx file to implement the settings page design following the figma file to pixel perfect implementation. I will also make sure the page is fully responsive before making a PR
ETA - 1 day.

**Comment by JosueBrenes** [comment]
## [FE]: Create Settings Page

Hi, I'm Josué Brenes and I'll be working on this issue.  
I'm a Dojo Coding member. ⛩️  

I estimate this will take 1 day to complete.

---

### Steps to Resolve

1. **Understand the Design**  
   - Review the provided Figma design to understand the structure and components required for the Settings page.

2. **Setup the Page**  
   - Navigate to `src/components/settings/SettingsComponent.tsx`.
   - Use the pre-configured route `/settings` to render the component.

3. **Implement the Design**  
   - Strictly follow the Figma design to replicate the layout and styling.  
   - For the **profile picture upload section**, utilize the pre-built component `src/components/ui/UploadPhotoProfile.tsx`.

4. **Testing**  
   - Verify the implementation by running the application and navigating to `/settings`.
   - Ensure the page is responsive and aligns with the design across different screen sizes.

5. **Final Review**  
   - Cross-check the implementation with the Figma design for consistency.  
   - Test the functionality of the `UploadPhotoProfile` component to ensure it works as expected.

6. **Submit Changes**  
   - Commit the changes to a new branch named `feature/settings-page`.  
   - Open a pull request with a detailed summary of the work done.

---

### Expected Outcome

A fully functional and design-compliant Settings page, accessible via the `/settings` route, with a working profile picture upload feature.

---

**Comment by SYLVIANNORUKA** [comment]
May I pick this up?
I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, . I would love to contribute to this project.

**Comment by wheval** [comment]
Hello, I'd love to give this a go.
I'm an experienced frontend developer.
I have read the process, pretty straigtforward. I would ensure i build a pixel perfect implementation of the Figma design.

ETA is 1 day.

**Comment by Emmanex01** [comment]
Can I take care of this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 2days.

**Comment by 7-falseparfait** [comment]
Could I take on this issue?

I am a Front-end and Smart Contract Developer with expertise in Tailwind CSS, Next.js, TypeScript, and JavaScript. I am eager to contribute to this project and bring value with my skills.

**Comment by Ekene001** [comment]
I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table.
Please Can i be assigned to this task

**Comment by Emmykeyz101** [comment]
I'd like to handle this task.

**Comment by kcmikee** [comment]
Can I take care of this issue?

**Comment by markdavid000** [comment]
## About Me
I’m a blockchain and frontend developer passionate about creating decentralized applications. I have hands-on experience developing smart contracts on EVM-compatible blockchains using Solidity. I focus on building secure and efficient systems while crafting intuitive user interfaces to bridge the gap between complex blockchain technology and everyday users.

## Solution Plan
After carefully going through the codebase on GitHub and the Figma design, 
- I will write the code to Implement the Settings UI in the `SettingsComponent.tsx` file.
- I will follow and maintain the codebase structure using TypeScript, Nextjs, TailwindCSS e.t.c
- I will ensure the design is responsive and works across all devices

## ETA
3-4 Hours

**Comment by austineblaise** [comment]
**How I Can Solve the Issue**  

As a JavaScript blockchain developer, I will implement the `/settings` page by adhering to the Figma design and ensuring seamless functionality. Using the `SettingsComponent.tsx` file, I’ll create a responsive and interactive UI, integrating the `UploadPhotoProfile.tsx` component for profile uploads. My expertise in JavaScript ensures efficient and maintainable code aligned with the project’s standards and Contributors Guide.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by abdegenius** [comment]
Is this issue still available?

**Comment by 0xdevcollins** [comment]
Could I try solving this?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 12 OnlyDust projects.

**Comment by Yunusabdul38** [comment]
Estimated Completion Time (ETA): I estimate completing this issue within 2 days.

Plan:
Understand Design Requirements: Review the Figma design thoroughly to ensure accurate implementation.

Set Up Layout: Begin by structuring the SettingsComponent.tsx to match the layout in the Figma design 

Styling: styled the components to adhere strictly to the design guidelines. and ensuring responsiveness and accessibility.

Test: Validate the page functionality and appearance across different devices and browsers.

Submit for Review: Ensure the implementation meets all requirements before creating a pull request.

**Comment by derianrddev** [comment]
**Hello StarShop Team,**

I am **Derian Rodríguez**, a member of the **Dojo Coding** community ⛩️💻. I’m excited to contribute to your **Stellar**-based project during the **Only Dust Hackathon #11** 🚀.

As a **full-stack** developer, I have experience in:

- **Frontend:** JavaScript/TypeScript, TailwindCSS, React, Next.js, and shadcn/ui.
- **Backend:** Node.js (Express.js, Nest.js).
- **Web3:** Cairo.

### Plan to Address the *Issue*

1. Edit the `SettingsComponent.tsx` file located in `src/components/settings/`.
2. Build the Settings page according to the exact design provided in the Figma file.
3. Ensure that the styles are responsive and consistent with the overall UI of the application.
4. Verify functionality and ensure a smooth user experience.

Here are my profiles:

- [**GitHub**](https://github.com/derianrddev)
- [**OnlyDust**](https://app.onlydust.com/u/derianrddev)

Thank you for considering my application.

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a frontend and smart contract developer. I promise to write a pixel perfect code.

**Comment by jedstroke** [comment]
I'd like to take this issue my ETA will be 3 days

**Comment by Michaelkingsdev** [comment]
I'd love to give this a go.

**Comment by trashcancries** [comment]
I am a frontend dev with 2 years of experience in React.

Since the route and component is already configured, I would write the code for the UI and make sure it also matches the rest of the UI in the webpage.

eta: 3 days

**Comment by Bran18** [comment]
Hello Team,

My name is Brandon Andrey Fernandez, and I am part of the Dojo Coding Community ⛩️💻 and https://bitcash.org/en. I’m excited about the opportunity to contribute to your project during Only Dust Hackathon #12! 🚀

I am a full-stack developer with experience in Web3 and blockchain technologies, particularly in projects involving smart contracts, AI integration, and decentralized solutions. I have worked on a large number of web3 projects and solutions as for example: 

https://masterbots.ai/
https://bitlauncher.ai/en

I am interested in this specific issue because it combines my passions: blockchain, AI technology, and modern web development. I am motivated by the opportunity to improve my skills and contribute to the project. I have participated in hackathons like ODH and other web2 based hackathons.

During the hackathon, I can dedicate approximately 5h min hours per day to working on this issue. I am committed to active collaboration, delivering high-quality code, and maintaining open communication with the team.

You can find my profiles and links here:

• GitHub: https://github.com/Bran18?tab=repositories
• OnlyDust: https://app.onlydust.com/u/Bran18
• X: https://x.com/branfdez_18
• LinkedIn: https://www.linkedin.com/in/brandonfdez18/

Thank you for considering my application. Please let me know if you have any questions or need any additional information.

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience in back-end development, including designing and handling APIs, optimizing server-side logic, and ensuring secure and efficient data handling.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by JoelVR17** [comment]
### Request to Work on Settings Page Implementation  

Hello, team!  

I would like to take on the task of implementing the **Settings Page** as described in the issue. I’ll ensure the following steps are carried out precisely according to the guidelines:  

#### Plan of Action:  
1. **File Usage**:  
   - Utilize the existing component located at `src/components/settings/SettingsComponent.tsx` to implement the Settings Page.  

2. **Design Adherence**:  
   - Follow the provided Figma design meticulously to ensure the page aligns with the overall application’s style.  

3. **Image Upload Section**:  
   - Integrate the `src/components/ui/UploadPhotoProfile.tsx` component for the image upload section as instructed.  

#### Acceptance Criteria:  
- The Settings Page is implemented strictly following the Figma design.  
- The `UploadPhotoProfile` component is integrated seamlessly.  
- The page is responsive and consistent with the rest of the application.  

I will ensure the final implementation meets all the requirements and follows the Contributor’s Guide. Let me know if there are additional details or expectations for this task.  

Thank you!  
**Joel Vargas**

**Comment by Supa-mega** [comment]
Would love to tackle this!

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,

I’d be thrilled to work on this issue as I have extensive experience with front-end technologies, including React and Next.js.

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!  


Looking forward to contributing!

**Comment by therealemino** [comment]
Hi, I've over 4 years of professional experience, working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. This would be nice for my first issue, can it be assigned to me?

**Comment by Kachimercy1** [comment]
Can I jump on this task?

**Comment by kayceeDev** [comment]
May I be assigned to this?

**Comment by davedumto** [comment]
Hi I am David, I am a frontend web developer that specializes in Typescript, Javascript and tailwindcss. I plan to approach this issue by building the "Settings" page to be according the Figma design and also responsive. ETA 2 days

**Comment by Akshola00** [comment]
i would like to work on this issue 
I'm Akinshola Akinniyi 
a frontend developer and I have experience with building seamless fronted interfaces 
pls assign this to me 
eta 1 day

**Comment by blessingbytes** [comment]
I’d like to resolve this.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by FrankiePower** [comment]
I am Super Franky, a frontend developer and recent graduate from web3bridge africa, the premier and biggest blockhain developer community in Africa. I can create the settings page. l start out with studying the figma file, breaking down the necessary components and begin building out the UI. The project timeline estimate is 1-2 days.

**Comment by akintewe** [comment]
Hey there!
I'm Oluwasola, and I'm pumped to work on this Settings page! I've got solid React and TypeScript skills, and I'm all about making interfaces look awesome. I've checked out the Contributors Guide and I'm ready to nail this design.
I'll make sure the Settings page looks exactly like the Figma design - down to the last pixel. Can't wait to dive in and make this happen!  ETA 12hours

**Comment by ShantelPeters** [comment]
I'd love to work on this!

**Comment by Amarjeet325** [comment]
Is it okay if I tackle this?

**Comment by sonkeydotcom** [comment]
Id be thrilled to take this. ETA: less than 24hrs, will be implementing a pixel perfect layout that is responsive on both desktop and mobile

**Comment by QuiqueCode** [comment]
## 👤 **Personal information**
My name is Dylan Castillo, a developer passionate about technology and computing. I have a focus on frontend development, where I am constantly learning and evolving. I have experience in creating dynamic and functional applications using React. I always seek to develop efficient, scalable solutions focused on user experience.

## 🧢 **OnlyDust Info**

I’ve contributed to a project on the OnlyDust platform. Check out my profile on [OnlyDust](https://app.onlydust.com/u/QuiqueCode) to learn more about my work.

## 🛠 **General Project Requirements**

Implement the Settings page for the application based on the provided design specifications and requirements. This task involves creating a responsive, user-friendly interface that adheres strictly to the design.


## 💡 **Proposal**

To implement the Settings page, the following steps are proposed:

1.  **Setup and Review**:
    
    -   Open the component file located at `src/components/settings/SettingsComponent.tsx`.
        
    -   Review the Figma design linked in the issue to understand layout, colors, typography, and any specific interactive elements.
        
2.  **Component Structure**:
    
    -   Divide the page into reusable subcomponents as per the design.
        
    -   Ensure proper nesting and accessibility using semantic HTML tags.

## 🌟 **Benefits**

-   **Improved User Experience**:
    
    -   A visually appealing and functional Settings page enhances user satisfaction and engagement.
    -   Incorporating accessibility practices ensures the page is usable by all audiences, including people with disabilities, providing an inclusive experience.
-   **Consistency**:
    -   Strict adherence to the Figma design ensures consistency across the application..

- **ETA**: 1-3 days

**Comment by KevinLatino** [comment]
@JoelVR17 Task assigned to you. Let me know if you need further clarification or additional support! 😊
Here is our telegram group, please join https://t.me/starshopcr

**Comment by JoelVR17** [comment]
> @JoelVR17 Task assigned to you. Let me know if you need further clarification or additional support! 😊 Here is our telegram group, please join https://t.me/starshopcr

Thanks!!

I'll work on it!
